---
# tasks file for cpm_validateparameters
- name: check EULA is accepted
  fail:
    msg: "You must accept EULA to start the playbook"
  when: accept_eula|lower != "yes"

- name: check if cpm_zip_file_path undefined
  fail: 
    msg: "cpm_zip_file_path is undefined, failing..."
  when: cpm_zip_file_path is not defined

- name: check if cpm_zip_file_path exists
  stat:
    path="{{ cpm_zip_file_path }}"
  register: st
  delegate_to: localhost
  
- fail: 
    msg: "{{ cpm_zip_file_path }} not exists, failing..."
  when: not st.stat.exists

- name: check if cpm was already installed
  win_service: 
    name: "{{ cpm_service_name }}"
  register: cpm_service_info
  
- name: check if cpm scanner was already installed
  win_service: 
    name: "{{ cpm_scanner_service_name }}"
  register: cpm_scanner_service_info

- set_fact:
    cpm_exists: "{{ cpm_service_info.exists }}"
    cpm_scanner_exists: "{{ cpm_scanner_service_info.exists }}"

- name: check if cpm is hardened
  set_fact: 
    cpm_hardened: true
  when:
    - cpm_exists and cpm_scanner_exists
    - cpm_service_info.username != "LocalSystem" and cpm_scanner_service_info.username != "LocalSystem"


- name: check if cpm is registered
  set_fact:
    cpm_registered: true
  when: 
    - cpm_exists and cpm_scanner_exists
    - cpm_service_info.state == "running" and cpm_scanner_service_info.state == "running"  
    