---
# tasks file for cpm installation

- name: set installation folder on xml config file
  win_shell: |
    try
    {
        ### This script set the install directory received from var in the install config file
        $filePath = "{{ cpm_installationautomation_folder }}\\Installation\\InstallationConfig.xml"
        $xml = [xml](Get-Content $filePath)
        $step = $xml.SelectSingleNode("//Parameter[@Name = 'CPMInstallDirectory']")
        $step.Value = "{{ cpm_installation_path }}"
        $xml.Save($filePath)
        exit 0
    }
    catch
    {
        Write-Output "Error occured during SetAtrributeInXML"
        exit 1
    }

- name: run CPM installation
  win_shell: |
    ### This script install CPM, set the json result to local variable and read it 
    Set-Location "{{ cpm_installationautomation_folder }}\Installation"
    $Action = .\CPMInstallation.ps1
    $Action | Out-File -FilePath "{{ cpm_installationautomation_folder }}\cpm_installation_result.txt"
    $Result = Get-Content "{{ cpm_installationautomation_folder }}\cpm_installation_result.txt" | ConvertFrom-Json
    if ($Result.isSucceeded -eq 2) {
      exit 1
    } else {
      exit 0
    }
  args:
    chdir: "{{ cpm_installationautomation_folder }}\\Installation"

- name: Validate CPM installation
  win_shell: |
    If ((Select-String -path "{{ cpm_installationautomation_folder }}\Installation\Script.log" -Pattern "Operation Succeeded") -eq $null) 
    {exit 1} else {exit 0}

- name: check if cpm service created successfully
  win_service: 
    name: "{{ cpm_service_name }}"
  register: cpm_service_info
  
- name: check if cpm scanner created successfully
  win_service: 
    name: "{{ cpm_scanner_service_name }}"
  register: cpm_scanner_service_info

- set_fact:
    cpm_exists: "{{ cpm_service_info.exists }}"
    cpm_scanner_exists: "{{ cpm_scanner_service_info.exists }}"